# Form implementation generated from reading ui file 'drone.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(394, 73)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_sp = QtWidgets.QLabel(parent=Form)
        self.label_sp.setObjectName("label_sp")
        self.gridLayout.addWidget(self.label_sp, 1, 0, 1, 1)
        self.label_md = QtWidgets.QLabel(parent=Form)
        self.label_md.setObjectName("label_md")
        self.gridLayout.addWidget(self.label_md, 0, 0, 1, 1)
        self.label_drone_model = QtWidgets.QLabel(parent=Form)
        self.label_drone_model.setObjectName("label_drone_model")
        self.gridLayout.addWidget(self.label_drone_model, 0, 1, 1, 2)
        self.label_spare_batt = QtWidgets.QLabel(parent=Form)
        self.label_spare_batt.setObjectName("label_spare_batt")
        self.gridLayout.addWidget(self.label_spare_batt, 1, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_sp.setText(_translate("Form", "Spare Batt:"))
        self.label_md.setText(_translate("Form", "Model:"))
        self.label_drone_model.setText(_translate("Form", "TextLabel"))
        self.label_spare_batt.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
