# Form implementation generated from reading ui file 'drone_pre.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(130, 50)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.model_text = QtWidgets.QLabel(parent=Form)
        self.model_text.setText("")
        self.model_text.setObjectName("model_text")
        self.gridLayout.addWidget(self.model_text, 1, 3, 1, 2)
        self.spare_batt_label = QtWidgets.QLabel(parent=Form)
        self.spare_batt_label.setObjectName("spare_batt_label")
        self.gridLayout.addWidget(self.spare_batt_label, 2, 1, 1, 1)
        self.model_label = QtWidgets.QLabel(parent=Form)
        self.model_label.setObjectName("model_label")
        self.gridLayout.addWidget(self.model_label, 1, 1, 1, 1)
        self.spare_batt_text = QtWidgets.QLabel(parent=Form)
        self.spare_batt_text.setText("")
        self.spare_batt_text.setObjectName("spare_batt_text")
        self.gridLayout.addWidget(self.spare_batt_text, 2, 3, 1, 2)
        self.colon_2 = QtWidgets.QLabel(parent=Form)
        self.colon_2.setObjectName("colon_2")
        self.gridLayout.addWidget(self.colon_2, 1, 2, 1, 1)
        self.colon_3 = QtWidgets.QLabel(parent=Form)
        self.colon_3.setObjectName("colon_3")
        self.gridLayout.addWidget(self.colon_3, 2, 2, 1, 1)
        self.id_text = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.id_text.setFont(font)
        self.id_text.setObjectName("id_text")
        self.gridLayout.addWidget(self.id_text, 1, 0, 2, 1)
        self.gridLayout.setColumnStretch(4, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.spare_batt_label.setText(_translate("Form", "Spare Batt"))
        self.model_label.setText(_translate("Form", "Model"))
        self.colon_2.setText(_translate("Form", ":"))
        self.colon_3.setText(_translate("Form", ":"))
        self.id_text.setText(_translate("Form", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
