# Form implementation generated from reading ui file 'drone_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.model_label = QtWidgets.QLabel(parent=Dialog)
        self.model_label.setObjectName("model_label")
        self.verticalLayout.addWidget(self.model_label)
        self.model_combo = QtWidgets.QComboBox(parent=Dialog)
        self.model_combo.setObjectName("model_combo")
        self.model_combo.addItem("")
        self.model_combo.addItem("")
        self.verticalLayout.addWidget(self.model_combo)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.ip_label = QtWidgets.QLabel(parent=Dialog)
        self.ip_label.setObjectName("ip_label")
        self.verticalLayout.addWidget(self.ip_label)
        self.ip_text = QtWidgets.QLineEdit(parent=Dialog)
        self.ip_text.setText("")
        self.ip_text.setObjectName("ip_text")
        self.verticalLayout.addWidget(self.ip_text)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.spare_label = QtWidgets.QLabel(parent=Dialog)
        self.spare_label.setObjectName("spare_label")
        self.verticalLayout.addWidget(self.spare_label)
        self.spare_spin = QtWidgets.QSpinBox(parent=Dialog)
        self.spare_spin.setObjectName("spare_spin")
        self.verticalLayout.addWidget(self.spare_spin)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create a New Drone"))
        self.model_label.setText(_translate("Dialog", "Select Drone Model:"))
        self.model_combo.setItemText(0, _translate("Dialog", "Parrot Anafi 4k"))
        self.model_combo.setItemText(1, _translate("Dialog", "Parrot Anafi USA"))
        self.ip_label.setText(_translate("Dialog", "Enter Ip Address:"))
        self.ip_text.setPlaceholderText(_translate("Dialog", "1.2.3.4 for Test Drones"))
        self.spare_label.setText(_translate("Dialog", "Enter Number of Spare Battery:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
