# Form implementation generated from reading ui file 'drone.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(394, 78)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.model_text = QtWidgets.QLabel(parent=Form)
        self.model_text.setObjectName("model_text")
        self.gridLayout.addWidget(self.model_text, 1, 1, 1, 2)
        self.spare_batt_text = QtWidgets.QLabel(parent=Form)
        self.spare_batt_text.setObjectName("spare_batt_text")
        self.gridLayout.addWidget(self.spare_batt_text, 2, 1, 1, 2)
        self.spare_batt_label = QtWidgets.QLabel(parent=Form)
        self.spare_batt_label.setObjectName("spare_batt_label")
        self.gridLayout.addWidget(self.spare_batt_label, 2, 0, 1, 1)
        self.model_label = QtWidgets.QLabel(parent=Form)
        self.model_label.setObjectName("model_label")
        self.gridLayout.addWidget(self.model_label, 1, 0, 1, 1)
        self.id_label = QtWidgets.QLabel(parent=Form)
        self.id_label.setObjectName("id_label")
        self.gridLayout.addWidget(self.id_label, 0, 0, 1, 1)
        self.id_text = QtWidgets.QLabel(parent=Form)
        self.id_text.setObjectName("id_text")
        self.gridLayout.addWidget(self.id_text, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.model_text.setText(_translate("Form", "TextLabel"))
        self.spare_batt_text.setText(_translate("Form", "TextLabel"))
        self.spare_batt_label.setText(_translate("Form", "Spare Batt:"))
        self.model_label.setText(_translate("Form", "Model:"))
        self.id_label.setText(_translate("Form", "ID:"))
        self.id_text.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
